- name: Install Zabbix 7 LTS in Rocky 9
  hosts: web1
  become: true
  tasks:
         
   - name: Add repository
     yum:
       disable_gpg_check: yes
       pkg: https://repo.zabbix.com/zabbix/7.0/rocky/9/x86_64/zabbix-release-7.0-2.el9.noarch.rpm    
       state: present       